// This file is automatically generated. Do not modify it manually.
// This file is used to store the Firebase configuration.
// It is created automatically by the Firebase Studio.

export const firebaseConfig = {
  "projectId": "studio-5446065759-8b2ba",
  "appId": "1:864164662429:web:62fdd41f6bbf37ae2fd874",
  "apiKey": "AIzaSyAtFJEtkoEXDigCpXlH4B35D0ZEg3lKTOU",
  "authDomain": "studio-5446065759-8b2ba.firebaseapp.com",
  "storageBucket": "studio-5446065759-8b2ba.appspot.com",
  "messagingSenderId": "864164662429"
};
